### ISSUE TITLE
PNGCrush was unable to optimise image

### ISSUE THREAD

**Issue by tremby** [bensquire/php-image-optim#2]
With pngcrush 1.7.65, 1.7.76, and 1.7.78, php-image-optim fails. It is trying to run the command

    $this->binaryPath . ' -rem gAMA -rem cHRM -rem iCCP -rem sRGB -brute -l 9 -max -reduce -m 0 -q ' . $this->imagePath

There's an error here: `-max` expects an argument. Omitting `-max` leads to progress, but has the warning `Ignoring invalid method: 0`.

After that is changed we still get an error, though running it on the command line doesn't give one (but doesn't change the file). Adding the `-ow` (overwrite) option leads to a working command.

However, there's one further issue, in that if the current directory (i.e. `getcwd()`) isn't writable by the user PHP is running as, the command fails because pngcrush attempts to write a temporary file (`pngout.png`) in there. So switching temporarily to `sys_get_temp_dir()` should do the trick.

I guess the command was written with an older version of pngcrush in mind.

It might be a good idea to either detect the version and modify as necessary or to just support current versions.

**Comment by bensquire** [comment]
@tremby Thanks, I've have this working now for v1.8.0.

**Comment by tremby** [comment]
Can you point me to the commit? Or was it a pngcrush change which fixed it? I don't see any obviously relevant commit messages on the master branch.

**Comment by bensquire** [comment]
@tremby They are very scrappy commits apologies about that:

https://github.com/bensquire/php-image-optim/commit/e18dbdcb2056b63a4b816ba12760869347532c00#diff-942f9ba8fb3f78b0c51f922cf42b6518

I'm also using PngCrush 1.8.0. Please let me know if you think I'm wrong

**Comment by tremby** [comment]
Correct me if I

**Comment by tremby** [comment]
Correct me if I'm wrong (I haven't tested the code -- the project where I was using this is long over), but I don't think you've fixed the second half of the bug report, where I mentioned that pngcrush wants to write temporary files to the current working directory. For that reason, it was necessary in my use case to have php-image-optim change directory to elsewhere (somewhere it could definitely write) before running the binary, then change back again. The code to fix this is still in the branch I linked to.

**Comment by tremby** [comment]
I've rebased it on current master, in case it's helpful, and changed the commit message (since it was no longer strictly correct). PR open at #5.
