### ISSUE TITLE
Recent update and lack of tags broken our setup.

### ISSUE THREAD

**Issue by snsmurf** [bensquire/php-image-optim#6]
Would it be possible for you to start using tags and releases? One of your commits 7 days ago, bumping the PHP requirement was a breaking change and consequently our composer updates are now failing due to us currently running 5.5 for legacy reasons (as I suspect numerous other peoples will be that could be using your package).

Any chance you could go back and tag this commit with major tag https://github.com/bensquire/php-image-optim/commit/b754e9e0f4a16bf5693c548daf9480922f6e30a3

And then tag the latest commit with an increment to the Major version number.

Incase there's any confusion with versioning, can I suggest you checkout http://semver.org

Cheers,
Mike

**Comment by bensquire** [comment]
@snsmurf See releases, I think I have this in state that meets what you require. You'll want the tag: https://github.com/bensquire/php-image-optim/commit/b754e9e0f4a16bf5693c548daf9480922f6e30a3
